services:
  - type: web
    name: baguio-pet-boarding-backend
    env: node
    region: singapore
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SUPABASE_HOST
        sync: false
      - key: SUPABASE_PORT
        sync: false
      - key: SUPABASE_USER
        sync: false
      - key: SUPABASE_PASSWORD
        sync: false
      - key: SUPABASE_DATABASE
        sync: false
      - key: JWT_SECRET
        generateValue: true
    healthCheckPath: /api/health
    autoDeploy: true
